import React from 'react';

const WorkInstructions = () => {
	return (
		<section>
			<sub id='workInstructions'></sub>
			<h2>Work Instructions <a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Forms/AllItems.aspx?FilterField1=OCT%5Fx0020%5FOperational%5Fx0020%5FDocument%5Fx0020%5FType&FilterValue1=Work%20Instruction&FilterType1=Lookup&FilterDisplay1=Work%20Instruction&viewid=bc80df01%2D823b%2D4aba%2Da1f9%2D13e8c7ddfa17' target='_blank' rel="noreferrer">(All Here)</a></h2>
			<h3>Emergency</h3>
			<ul>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Fire%20or%20Smoke%20Incidents.pdf' target='_blank' rel="noreferrer">Fire and Smoke</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Train%20Human%20Contact.pdf' target='_blank' rel="noreferrer">Train Human Contact</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Bomb%20Threat.pdf' target='_blank' rel="noreferrer">Bomb Threat</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Civil%20Unrest.pdf' target='_blank' rel="noreferrer">Civil Unrest/Riot</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Suspicious%20Package.pdf' target='_blank' rel="noreferrer">Suspicious Package</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/CBRN%20-%20Chemical%20Biological%20Radiological%20and%20Nuclear%20Incident.pdf' target='_blank' rel="noreferrer">CBRNE (Chem, Bio, Radioax, Nuclear, Explosive)</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Employee%20Emergency%20Alarm.pdf' target='_blank' rel="noreferrer">Employee Emergency Alarm</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Extreme%20Weather%20Events.pdf' target='_blank' rel="noreferrer">Extreme Weather Events</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperations/TOCCOperationalDocumentation/Forms/AllItems.aspx?id=%2Fsites%2FRailOperations%2FTOCCOperationalDocumentation%2FTOCC%2DS100%2D03%2DWI%2DRev1%2E0%2DSeismic%20Events%202017%2D11%2D22%2Epdf&parent=%2Fsites%2FRailOperations%2FTOCCOperationalDocumentation' target='_blank' rel="noreferrer">Seismic Events (Earthquakes)</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/P%2025%20Radio%20Failure%20-%20Line%201.pdf?CT=1613417000354&OR=ItemsView&siteid={9F3D765B-F6C6-42B8-829C-48774268CF1D}&webid={A5B7FA5B-F68A-4A43-9A9C-F235B73A1207}&uniqueid={F819E995-B00A-4614-B5C9-5EFA32D53EB3}' target='_blank' rel="noreferrer">P25 Radio Failure</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Forms/AllItems.aspx?id=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation%2FLine%20Of%20Sight%20Operations%20On%20The%20Confederation%20Line%2Epdf&parent=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation' target='_blank' rel="noreferrer">Line of Sight</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Forms/Group%20By%20Document%20Type.aspx?id=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation%2FSystem%20and%20Station%20Status%20and%20Failures%2Epdf&parent=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation' target='_blank' rel="noreferrer">Power Interruption (Section 9)</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Forms/AllItems.aspx?q=gids&id=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation%2FResponding%20to%20Trespassers%20%26%20GIDS%20on%20the%20Confederation%20Line%2Epdf&parent=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation&parentview=7' target='_blank' rel="noreferrer">Trespasser (GIDS)</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperations/TOCCOperationalDocumentation/Forms/AllItems.aspx?id=%2Fsites%2FRailOperations%2FTOCCOperationalDocumentation%2FTOCC%2DS100%2D17%2DWI%2DRev1%2E0%2DEmployee%20Emergency%20Alarm%2D2018%2D01%2D09%2Epdf&parent=%2Fsites%2FRailOperations%2FTOCCOperationalDocumentation' target='_blank' rel="noreferrer">Employee Emergency Alarm (EA)</a></li>
			</ul>
			<h3>Procedural</h3>
			<ul>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Forms/Group%20By%20Document%20Type.aspx?id=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation%2FSystem%20and%20Station%20Status%20and%20Failures%2Epdf&parent=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation' target='_blank' rel="noreferrer">System and Station Status and Failures</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Forms/Group%20By%20Document%20Type.aspx?id=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation%2FManaging%20Disturbed%20and%20Trailed%20Switch%20Zones%2Epdf&parent=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation' target='_blank' rel="noreferrer">Disturbed AND Trailed Switch</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Forms/Group%20By%20Document%20Type.aspx?id=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation%2FActivation%20of%20Line%201%20Back%20Up%20Control%20Center%2Epdf&parent=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation' target='_blank' rel="noreferrer">Activation of Backup Control Center (BCC)</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Forms/Group%20By%20Document%20Type.aspx?id=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation%2FTemporary%20Speed%20Restrictions%2Epdf&parent=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation' target='_blank' rel="noreferrer">Temporary Speed Restrictions (TSR)</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Forms/AllItems.aspx?FilterField1=OCT%5Fx0020%5FOperational%5Fx0020%5FDocument%5Fx0020%5FType&FilterValue1=Work%20Instruction&FilterType1=Lookup&FilterDisplay1=Work%20Instruction&id=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation%2FWork%20Zones%2Epdf&parent=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation' target='_blank' rel="noreferrer">Work Zones</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperations/TOCCOperationalDocumentation/Forms/AllItems.aspx?id=%2Fsites%2FRailOperations%2FTOCCOperationalDocumentation%2FTOCC%2DS100%2D24%2DWI%2DRev3%2E0%2DElevator%20and%20Escalator%20Failure%20or%20Incident%2D2019%2D10%2D21%2Epdf&parent=%2Fsites%2FRailOperations%2FTOCCOperationalDocumentation' target='_blank' rel="noreferrer">Escalator/Elevator Failures/Incidents</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperations/TOCCOperationalDocumentation/Forms/AllItems.aspx?id=%2Fsites%2FRailOperations%2FTOCCOperationalDocumentation%2FTOCC%2DQ090%2D02%2DSD%2DRev1%2E1%2DElectric%20Rail%20Controller%20Roles%20and%20Responsibilities%2D2019%2D12%2D17%2Epdf&parent=%2Fsites%2FRailOperations%2FTOCCOperationalDocumentation' target='_blank' rel="noreferrer">ERC Roles and Responsibilities</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Forms/AllItems.aspx?q=cctv&id=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation%2FClosed%20Circuit%20Television%20Control%20Line%201%2Epdf&parent=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation&parentview=7' target='_blank' rel="noreferrer">CCTV</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Forms/AllItems.aspx?q=cctv&id=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation%2FTunnel%20Ventilation%20System%2Epdf&parent=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation&parentview=7' target='_blank' rel="noreferrer">Tunnel Ventilation System (TVS)</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Use%20of%20Non-Emergency%20TVS%20Modes.pdf?CT=1656884653816&OR=ItemsView' target='_blank' rel="noreferrer">Non-Emergency TVS</a></li>
				<li><a href='https://ottawacity.sharepoint.com/sites/RailOperationsDocumentControl/OCTOperationalDocumentation/Forms/AllItems.aspx?q=cctv&id=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation%2FEvacuations%20on%20the%20Confederation%20Line%2Epdf&parent=%2Fsites%2FRailOperationsDocumentControl%2FOCTOperationalDocumentation&parentview=7' target='_blank' rel="noreferrer">Evacuations</a></li>
			</ul>
		</section>
	);
};

export default WorkInstructions;
